baseurl: https://math.aurelienooms.be/
theme: events
title: Aurélien's Math Notebook
buildFuture: false

permalinks:
  post: /:year/:month/:day/:title

taxonomies:
  tag: tags
  author: authors

outputs:
  home:
    - HTML
    - RSS
    - JSON
  section:
    - HTML
    - RSS
  page:
    - HTML
  taxonomy:
    - HTML
    - RSS
  taxonomyTerm:
    - HTML

params:
  logo:
    src: /penrose-triangle.png
    alt: ULB
  organizer: 'CN="Aurélien Ooms":mailto:info@math.aurelienooms.be'
  hostname: math.aurelienooms.be
  editURL: https://github.com/aureooms/math
  nav:
    taxonomies:
      - tags
      - authors
  calendar:
    tzid: Europe/Brussels
    status:
      - CONFIRMED # Indicates event is definite.
      - TENTATIVE # Indicates event is tentative.
      - CANCELLED # Indicates event was cancelled.
    classification:
      - PUBLIC
      - PRIVATE
      - CONFIDENTIAL
  timeline: false
